### ISSUE TITLE
Developer Question 本地开发遇到的问题

### ISSUE THREAD

**Issue by Alndaly** [6174/comflowyspace#214]
我想在本地开发，但是在按照readme的文档跑项目的时候报这个错

之前开发electron项目的时候也遇到过，不过当初是用cnpm解决的，这里该怎么解决呢？以及这个报错的原因底层到底是啥=。= 

试了pnpm重新安装包，也试了本地turbo直接跑`turbo dev`，都不行，相同的报错

电脑💻：MacBookPro M1Pro
Node版本：v21.2.0
本地turbo版本：1.10.16

```
comflowy:dev: cache bypass, force executing 135a4361bd7fbad2
@comflowy/node:dev: cache bypass, force executing b6345e3ac365838e
:dev: cache bypass, force executing beb941ccd9d24a1f
comflowy:dev: 
comflowy:dev: > comflowy@0.0.8-alpha dev /Users/kinda/Developer/AI/comflowyspace/apps/electron-backend
comflowy:dev: > node scripts/esbuild.watch.mjs
comflowy:dev: 
:dev: 
:dev: > @ dev /Users/kinda/Developer/AI/comflowyspace/apps/electron-frontend
:dev: > cross-env NODE_ENV=development node ./scripts/server.js
:dev: 
@comflowy/node:dev: 
@comflowy/node:dev: > @comflowy/node@0.0.0 dev /Users/kinda/Developer/AI/comflowyspace/apps/node
@comflowy/node:dev: > ts-node esbuild.config.mjs
@comflowy/node:dev: 
comflowy:dev: /Users/kinda/Developer/AI/comflowyspace/node_modules/.pnpm/electron@28.2.1/node_modules/electron/index.js:17
comflowy:dev:     throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again');
comflowy:dev:           ^
comflowy:dev: 
comflowy:dev: Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
comflowy:dev:     at getElectronPath (/Users/kinda/Developer/AI/comflowyspace/node_modules/.pnpm/electron@28.2.1/node_modules/electron/index.js:17:11)
comflowy:dev:     at Object.<anonymous> (/Users/kinda/Developer/AI/comflowyspace/node_modules/.pnpm/electron@28.2.1/node_modules/electron/index.js:21:18)
comflowy:dev:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
comflowy:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
comflowy:dev:     at Module.load (node:internal/modules/cjs/loader:1207:32)
comflowy:dev:     at Module._load (node:internal/modules/cjs/loader:1023:12)
comflowy:dev:     at cjsLoader (node:internal/modules/esm/translators:345:17)
comflowy:dev:     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
comflowy:dev:     at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
comflowy:dev:     at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
comflowy:dev: 
comflowy:dev: Node.js v21.2.0
comflowy:dev:  ELIFECYCLE  Command failed with exit code 1.
comflowy:dev: ERROR: command finished with error: command (/Users/kinda/Developer/AI/comflowyspace/apps/electron-backend) pnpm run dev exited (1)
comflowy#dev: command (/Users/kinda/Developer/AI/comflowyspace/apps/electron-backend) pnpm run dev exited (1)

 Tasks:    0 successful, 3 total
Cached:    0 cached, 3 total
  Time:    1.301s 
Failed:    comflowy#dev

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Alndaly** [comment]
翻了一下源码，我知道问题了，electron没有装完整，缺个dist目录和path.txt
