### ISSUE TITLE
MacOs  Intel安装失败 下面是报错

### ISSUE THREAD

**Issue by 1416246152** [6174/comflowyspace#255]
Using cached numpy-1.26.3-cp310-cp310-macosx_10_9_x86_64.whl.metadata (61 kB)
Collecting onnx==1.15.0
Using cached onnx-1.15.0-cp310-cp310-macosx_10_12_x86_64.whl.metadata (15 kB)
[31mERROR: Could not find a version that satisfies the requirement onnxruntime==1.17.0 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)[0m[31m [0m
[31mERROR: No matching distribution found for onnxruntime==1.17.0[0m[31m [0m
Traceback (most recent call last): File "/Users/dengdandan/Documents/ComfyUI/main.py", line 76, in <module>
import execution File "/Users/dengdandan/Documents/ComfyUI/execution.py", line 11, in <module>
import nodes File "/Users/dengdandan/Documents/ComfyUI/nodes.py", line 21, in <module>
import comfy.diffusers_load File "/Users/dengdandan/Documents/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
import comfy.sd File "/Users/dengdandan/Documents/ComfyUI/comfy/sd.py", line 5, in <module>
from comfy import model_management File "/Users/dengdandan/Documents/ComfyUI/comfy/model_management.py", line 119, in <module>
total_vram = get_total_memory(get_torch_device()) / (1024 * 1024) File "/Users/dengdandan/Documents/ComfyUI/comfy/model_management.py", line 88, in get_torch_device
return torch.device(torch.cuda.current_device()) File "/Users/dengdandan/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/cuda/__init__.py", line 803, in current_device
_lazy_init() File "/Users/dengdandan/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/cuda/__init__.py", line 309, in _lazy_init raise AssertionError("Torch not compiled with CUDA enabled") AssertionError: Torch not compiled with CUDA enabled
![screenshot-20240328-174442](https://github.com/6174/comflowyspace/assets/21049559/79bb2904-b06a-4ea7-9e8b-d99463854c65)

**Comment by mevernom** [comment]
> Torch not compiled with CUDA enabled

启动时没给 ComfyUI 加额外参数，默认就是走 CUDA。
你另外启动 ComfyUI 服务，加上 `--disable-cuda-malloc --use-split-cross-attention --cpu` 这几个参数就行。
ComfyUI 顺利运行后，再开 Comflowy 就行。

> --cpu： 就是指明使用CPU来画图（就是时间上会很慢）
> --disable-cuda-malloc： 指明不使用CUDA。
> --use-split-cross-attention ： 低内存的时候使用

**Comment by lgc2479794048** [comment]
你可以选择修改/Users/dengdandan/Documents/ComfyUI/comfy/model_management.py，强制使用cpu，修改get_torch_device函数，把最后一行修改成return torch.device("cpu")即可

**Comment by thinkingjimmy** [comment]
因为缺乏测试机，所以 Intel 版本我们后续应该会调低优先级。另外，我也不建议 Intel 的机器运行 ComfyUI 或 Comflowy，出图真的很慢很慢。
